### ISSUE TITLE
Question about eq.2 in the paper 

### ISSUE THREAD

**Issue by johnnylu305** [RahulSajnani/DRACO-Weakly-Supervised-Dense-Reconstruction-And-Canonicalization-of-Objects#1]
Hi, I have a question about equation 2 (smoothness loss) in the paper. I hope you can help me understand it. Does the equation mean multiply gradient with a depth map and nearby view (ex: delta_x * D^) or calculate the gradient of the depth map and nearby view? Computing the gradient of the depth map and nearby view makes sense for me. If it isn't, would you mind to explain more about it?

**Comment by RahulSajnani** [comment]
Hi @johnnylu305! Thank you for showing interest in our work! 
\delta_x \hat{D} - Computes the gradient of the depth map along the x direction and is weighted by e^{-|\delta_x I|}. Here, I is the image of the same view whose depth map is estimated. As |\delta_x I| increases, the exponential term reduces which ensures that the depth gradients are not penalized for smoothness. Having high image gradients most probably points out to change of object and hence the gradients of depth map are penalized lesser for smoothness. Here, delta is an operator that applied to depth map \hat{D} or image I that gives their respective gradients.

**Comment by johnnylu305** [comment]
Hi, @RahulSajnani  thank you for explaining it. I have some last questions about the code. 

In pose_vec2mat, why do we add 0.5 offsets, and why do we multiply the transformation matrix with invert_mat? Is it related to the dataset?

In inverse_warp, why src_cam_to_tgt_cam = tgt_pose_mat.inverse() @ src_pose_mat? 

I thought we will use tgt_pose_mat @ src_pose_mat.inverse() to get the target camera instead of tgt_pose_mat.inverse() @ src_pose_mat.

**Comment by RahulSajnani** [comment]
Hi @johnnylu305! The pose_vec2mat block that you are referring to isn't used in the current version of the code as I convert the matrix into a 4 x 4 matrix in the dataset itself ![here](https://github.com/RahulSajnani/DRACO-Weakly-Supervised-Dense-Reconstruction-And-Canonicalization-of-Objects/blob/d697905da990487589f88068c886a32d2ef57118/DRACO/Data_Loaders/data_loader.py#L335-L354). So it breaks out of ![this](https://github.com/RahulSajnani/DRACO-Weakly-Supervised-Dense-Reconstruction-And-Canonicalization-of-Objects/blob/d697905da990487589f88068c886a32d2ef57118/DRACO/inv_changed.py#L218-L221) block.

src_pose_mat transforms points from the camera frame to the world frame (<img src="https://render.githubusercontent.com/render/math?math=^{W}T_{C1}">) and tgt_pose_mat transforms points from camera frame 2 to world frame (<img src="https://render.githubusercontent.com/render/math?math=^{W}T_{C2}">). Therefore, to transform points from camera 1 (source) to camera 2 (target) we perform tgt_pose_mat.inverse() @ src_pose_mat = <img src="https://render.githubusercontent.com/render/math?math=(^{W}T_{C2})^{-1}"> @ (<img src="https://render.githubusercontent.com/render/math?math=^{W}T_{C1}">) = <img src="https://render.githubusercontent.com/render/math?math=^{C2}T_{C1}">
